name: Deploy dev app using AWS SSM Send-Command 

on:
  push:
    branches: [development]

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: AWS SSM Send Command
        uses: peterkimzz/aws-ssm-send-command@1.0.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY  }}
          aws-region: ap-southeast-2
          instance-ids: ${{ secrets.INSTANCE_ID  }}
          comment: Deploys the development branch
          working-directory: /home/ubuntu/it-project
          command: /bin/sh ./deploy.sh
