name: Node.js CI

on:
  push:
    branches: 
          - main
          - development
  pull_request:
    branches: 
          - main
          - development
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: 'Run ci on client'
      run: |
        cd client
        npm ci
    - name: 'Run ci on server'
      run: |
        cd server
        npm ci
    - name: 'Check build'
      run: |
        cd client
        npm run build 
    - name: 'Client test'
      env: 
        REACT_APP_AUTH0_DOMAIN: ${{secrets.REACT_APP_AUTH0_DOMAIN}}
        REACT_APP_AUTH0_CLIENT_ID: ${{secrets.REACT_APP_AUTH0_CLIENT_ID}}
        REACT_APP_DEV_URL: ${{secrets.REACT_APP_DEV_URL}}
        REACT_APP_PROD_URL: ${{secrets.REACT_APP_PROD_URL}}
      run: |
        cd client
        npm run test  
    - name: 'Server test'
      env:
        DB_CONN_URI: ${{secrets.DB_CONN_URI }}
        AUTH0_AUDIENCE: ${{secrets.AUTH0_AUDIENCE}}
      run: |
        cd server
        npm run test  
